### ISSUE TITLE
tx hash not found

### ISSUE THREAD

**Issue by fadlurhmn** [kj89/testnet_manuals#10]
root@sei-fad:~# seid tx staking create-validator \
> --amount=1000000usei \
> --pubkey=$(seid tendermint show-validator) \
> --moniker=fad \
> --chain-id=sei-testnet-2 \
> --from=sei1c95wnx8p3xt2up3yah88vk3uk0tylddcn6xxyl \
> --commission-rate="0.10" \
> --commission-max-rate="0.20" \
> --commission-max-change-rate="0.01" \
> --min-self-delegation="1"
Enter keyring passphrase:
incorrect passphrase
Enter keyring passphrase:
{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"fad","identity":"","website":"","security_contact":"","details":""},"commission":{"rate":"0.100000000000000000","max_rate":"0.200000000000000000","max_change_rate":"0.010000000000000000"},"min_self_delegation":"1","delegator_address":"sei1c95wnx8p3xt2up3yah88vk3uk0tylddcn6xxyl","validator_address":"seivaloper1c95wnx8p3xt2up3yah88vk3uk0tylddcd4hg90","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"Npbh8A8bYiZp6zO4e1GzUFQqW2qF9u+HIRsIcQGzhKw="},"value":{"denom":"usei","amount":"1000000"}}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
code: 19
codespace: sdk
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: ""
timestamp: ""
tx: null
txhash: A1F0F210C54E43E0E844F72FBF039A4F52673425DDA846C9C7B297676F767EBB

**Comment by kj89** [comment]
`--from` should not be your address instead it should be your wallet name
find wallet name using command 
```
seid keys list
```
