### ISSUE TITLE
seid status error

### ISSUE THREAD

**Issue by zhieaura** [kj89/testnet_manuals#11]
got this error after installing nodes
![Screenshot_55](https://user-images.githubusercontent.com/85457596/174500253-094bcd19-cf5a-4aef-8c73-d934cf548276.png)

**Comment by zhieaura** [comment]
tbh i dont know what im doing
im noobs
when i tried to check sync status with `seid status --node $SEI_RPC 2>&1 | jq .SyncInfo`
i got this messages `parse error: Invalid numeric literal at line 1, column 6`
But the block still running ( catching up )

Someon on discord tell me to check seid status and i got that messages.
im really sorry to bother u.

Im just tired 5 times reinstalling my vps and still get the same result , i cant check my sync status.

**Comment by kj89** [comment]
did you follow the guide and run Post installation step:
```
source $HOME/.bash_profile
```

**Comment by kj89** [comment]
the thing here that your node does not use standard ports anymore, so you have to pass `--node` argument with `$SEI_RPC` value to be able to execute commands. 

All variables are written in `~/.bash_profile` file and are loaded on startup.

So you have 2 options post installation:
1) restart the ssh session
2) run `source $HOME/.bash_profile` manually to load variables into system

**Comment by zhieaura** [comment]
omg its worked now when i put `source $HOME/.bash_profile` before `seid status --node $SEI_RPC 2>&1 | jq .SyncInfo`
thank u so much for helping me sir.
really apreciate
