### ISSUE TITLE
Remote ip port forwarding quicksilver hermes

### ISSUE THREAD

**Issue by jambulmerah** [kj89/testnet_manuals#20]
How to remote my quicksilver ip from my hermes vps, please add guides

**Comment by kj89** [comment]
its already in the guide
![image](https://user-images.githubusercontent.com/50621007/177031986-ec35737c-6106-4a85-9fcd-ef2af83f379e.png)

**Comment by kj89** [comment]
also check that port is opened in firewall

**Comment by kj89** [comment]
And also if you are having some issues please join our discord and ask there https://discord.gg/EY35ZzXY
