### ISSUE TITLE
SEI Network Issues

### ISSUE THREAD

**Issue by Shvetsman** [kj89/testnet_manuals#7]
Hello, after update i have problems with logs 

root@vmi897787:~/.sei# journalctl -u seid -f -o cat 
      --unsafe-skip-upgrades ints                       Skip a set of upgrade heights to continue the old binary
      --with-tendermint                                 Run abci app embedded in-process with tendermint (default true)
      --x-crisis-skip-assert-invariants                 Skip x/crisis invariants check on startup
Global Flags:
      --home string         directory for config and data (default "/root/.sei")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
seid.service: Main process exited, code=exited, status=1/FAILURE
seid.service: Failed with result 'exit-code'.
seid.service: Scheduled restart job, restart counter is at 69.
Stopped seid.
Started seid.
2:17PM INF starting node with ABCI Tendermint in-process
2:17PM INF Starting multiAppConn service impl=multiAppConn module=proxy
2:17PM INF Starting localClient service connection=query impl=localClient module=abci-client
2:17PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
2:17PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
2:17PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
2:17PM INF Starting EventBus service impl=EventBus module=events
2:17PM INF Starting PubSub service impl=PubSub module=pubsub
2:17PM INF Starting IndexerService service impl=IndexerService module=txindex
2:17PM INF ABCI Handshake App Info hash="�zR�~�f�\x06��Dh��X��\x05��_����h����;" height=1 module=consensus protocol-version=0 software-version=1.0.1beta
2:17PM INF ABCI Replay Blocks appHeight=1 module=consensus stateHeight=1 storeHeight=2
2:17PM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected EB7A529B7EBD668C068CF344688D8358DAC405A9BB5FB6CAC4F168DED0EFF73B, got 09EBC5080DB74B915DAD51FC14E6D283749618221AAAE6946C021C994EFCCE61
Usage:
  seid start [flags]
Flags:
      --abci string                                     specify abci transport (socket | grpc) (default "socket")
      --address string                                  Listen address (default "tcp://0.0.0.0:26658")
      --consensus.create_empty_blocks                   set this to false to only produce blocks when there are txs or when the AppHash changes (default true)
      --consensus.create_empty_blocks_interval string   the possible interval between empty blocks (default "0s")
      --consensus.double_sign_check_height int          how many blocks to look back to check existence of the node's consensus votes before joining consensus
      --cpu-profile string                              Enable CPU profiling and write to the provided file
      --db_backend string                               database backend: goleveldb | cleveldb | boltdb | rocksdb | badgerdb (default "goleveldb")
      --db_dir string                                   database directory (default "data")
      --fast_sync                                       fast blockchain syncing (default true)
      --genesis_hash bytesHex                           optional SHA-256 hash of the genesis file
      --grpc-only                                       Start the node in gRPC query only mode (no Tendermint process is started)
      --grpc-web.address string                         The gRPC-Web server address to listen on (default "0.0.0.0:9091")
      --grpc-web.enable                                 Define if the gRPC-Web server should be enabled. (Note: gRPC must also be enabled.) (default true)
      --grpc.address string                             the gRPC server address to listen on (default "0.0.0.0:9090")
      --grpc.enable                                     Define if the gRPC server should be enabled (default true)
      --halt-height uint                                Block height at which to gracefully halt the chain and shutdown the node
      --halt-time uint                                  Minimum block time (in Unix seconds) at which to gracefully halt the chain and shutdown the node
  -h, --help                                            help for start
      --inter-block-cache                               Enable inter-block caching (default true)
      --inv-check-period uint                           Assert registered invariants every N blocks
      --min-retain-blocks uint                          Minimum block height offset during ABCI commit to prune Tendermint blocks
      --minimum-gas-prices string                       Minimum gas prices to accept for transactions; Any fee in a tx must meet this minimum (e.g. 0.01photino;0.0001stake)
      --moniker string                                  node name (default "vmi897787.contaboserver.net")
      --p2p.laddr string                                node listen address. (0.0.0.0:0 means any interface, any port) (default "tcp://0.0.0.0:26656")
      --p2p.persistent_peers string                     comma-delimited ID@host:port persistent peers
      --p2p.pex                                         enable/disable Peer-Exchange (default true)
      --p2p.private_peer_ids string                     comma-delimited private peer IDs
      --p2p.seed_mode                                   enable/disable seed mode
      --p2p.seeds string                                comma-delimited ID@host:port seed nodes
      --p2p.unconditional_peer_ids string               comma-delimited IDs of unconditional peers
      --p2p.upnp                                        enable/disable UPNP port forwarding
      --priv_validator_laddr string                     socket address to listen on for connections from external priv_validator process
      --proxy_app string                                proxy app address, or one of: 'kvstore', 'persistent_kvstore', 'counter', 'e2e' or 'noop' for local testing. (default "tcp://127.0.0.1:26658")
      --pruning string                                  Pruning strategy (default|nothing|everything|custom) (default "default")
      --pruning-interval uint                           Height interval at which pruned heights are removed from disk (ignored if pruning is not 'custom')
      --pruning-keep-every uint                         Offset heights to keep on disk after 'keep-every' (ignored if pruning is not 'custom')
      --pruning-keep-recent uint                        Number of recent heights to keep on disk (ignored if pruning is not 'custom')
      --rpc.grpc_laddr string                           GRPC listen address (BroadcastTx only). Port required
      --rpc.laddr string                                RPC listen address. Port required (default "tcp://127.0.0.1:26657")
      --rpc.pprof_laddr string                          pprof listen address (https://golang.org/pkg/net/http/pprof)
      --rpc.unsafe                                      enabled unsafe rpc methods
      --state-sync.snapshot-interval uint               State sync snapshot interval
      --state-sync.snapshot-keep-recent uint32          State sync snapshot to keep (default 2)
      --trace-store string                              Enable KVStore tracing to an output file
      --transport string                                Transport protocol: socket, grpc (default "socket")
      --unsafe-skip-upgrades ints                       Skip a set of upgrade heights to continue the old binary
      --with-tendermint                                 Run abci app embedded in-process with tendermint (default true)
      --x-crisis-skip-assert-invariants                 Skip x/crisis invariants check on startup
Global Flags:
      --home string         directory for config and data (default "/root/.sei")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
seid.service: Main process exited, code=exited, status=1/FAILURE
seid.service: Failed with result 'exit-code'.
^C
root@vmi897787:~/.sei# cd
root@vmi897787:~# journalctl -u seid -f -o cat 
      --unsafe-skip-upgrades ints                       Skip a set of upgrade heights to continue the old binary
      --with-tendermint                                 Run abci app embedded in-process with tendermint (default true)
      --x-crisis-skip-assert-invariants                 Skip x/crisis invariants check on startup
Global Flags:
      --home string         directory for config and data (default "/root/.sei")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
seid.service: Main process exited, code=exited, status=1/FAILURE
seid.service: Failed with result 'exit-code'.
seid.service: Scheduled restart job, restart counter is at 71.
Stopped seid.
Started seid.

**Comment by kj89** [comment]
SEI Network chain currently is stuck on pre update state. We will have to wait for solution from a team. Currently every validator is experiencing the issue
