### ISSUE TITLE
Plz make script for arm64 ubuntu sytsem

### ISSUE THREAD

**Issue by gsweeh** [kj89/testnet_manuals#8]

**Comment by kj89** [comment]
Sorry i will not write scripts for arm. There is no much interest for that

**Comment by gsweeh** [comment]
I only have arm vps🥺 plz give time for this👏

**Comment by surajtadel09** [comment]
I also have arm64 Vps of Oracle ..Can u help to join in testnet?

**Comment by kj89** [comment]
sorry this will not happen, i have no free resources to waste on that
